# Generated by Django 5.2.6 on 2025-09-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('pet_type', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('owner_id', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Pets',
            },
        ),
    ]
