# Generated by Django 5.2.6 on 2025-09-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.TextField(),
        ),
    ]
