# Generated by Django 5.2.6 on 2025-09-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_alter_pet_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetData',
            fields=[
                ('pet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('miles_travelled', models.FloatField(blank=True, null=True)),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pet_data',
                'managed': False,
            },
        ),
    ]
